language: ruby
script:
- export RAILS_ENV=test
- bundle exec rake db:create db:schema:load db:test:prepare
- bundle exec rake cucumber
- bundle exec rspec --color --format documentation --require spec_helper --require rails_helper

deploy:
  provider: heroku
  api_key:
    secure: sTYWZqW3fOYEHHxAoaOf0luMfNPQ6Alcg9GGIRtutBV8yNp47SCCMszFoVwP2XlzkrTcfI5PczfspphcW/ryBdQzD083/dGgCnvMoUIIHunvwurGs33LfsUwLuJKFXnrnFplDrrdMWI+BMt6c+Wp1Z/bSFPIjA1PAqJyngvOdmBTyAHfYW/NbVTVbXqAnaQerQOV6BJPuccLeP5/001ncNSQxTKawNhbqpUFFD1KrmkP6+EvBHcMW4d4XSS94oUmLtTigijTV00NCZUV4l1WtBMsoOism5l/AY6CpOPjc2553U/sFN8agGj8F03hqY5Qls1B+AXv91c4nwvcTJju55RV3ChKFIy+miVQwSP848XpZ00sLszznaZaHpkYaST/8o22I+GaBPglquZUbzsRQmjNphZMJ1YYFmTNgGGvsbLu4EdCbix9YWVq1nMV02j3HZos2oto6JcJR18L3cldFxgm/+2BTQfwRKrno+IXOZZ9ORAenHty9cfYbOycEpw8helghl0PA7vCJ1Qws8bH0Kf53g0rK3BXEK+8Sgiz/SRi3vcWiX6r2iIz6G32wFs+OGIcrNU8r/Nqhlw5+iD8EowaiDHawZKhMhjKQHs04ZWbw5JZEtv92VWEEk2/mhiR6ouys7KTPy0LLaecrUHiL6XHBujwSxW+ODoEbvj7VJg=
  app: deeprog