language: ruby
script:
- export RAILS_ENV=test
- bundle exec rake db:create db:schema:load db:test:prepare
- bundle exec rake
addons:
  code_climate:
    repo_token: '088402be444ff5c274ba18d212dfe8ea518fba07ad7c768c00feb1f1aecf9b8a'
deploy:
  provider: heroku
  api_key:
    secure: CIVRM/JeEqJZkCR8/g5DOqDzkkPHYEmF4ESJWrUo85vVfx7RaWS5+gfBYYot6nppe+bLbJ/ei7XDnHEwoPiM7H3G03xorh+iP286m1XfBx00uCbU+HjETu4PprAezBYbPkjdAqn9FEOJxHG97ILMELIu5umbQo7MS9eTxsbBWUX5gR5QlaUjxR538YgzgAjGWHLMDsGUVfa/qXeAxHevFQ36khGkF9DFhb5aRKZ9hQL2jf8iUAfWoECNtFDBdZjMC7UItmDCxXw5q7AW4ohLbjnHoOYFnVdfbomwVyZqdd8Atc/RSY8LRjkxMx1wD+viqL98kHGVDLvgkaknSqFGaraoi+bXBj5DTIICNdtlR6b7vuuWyCg9nzy3hxbxeE/Q9BCUWsJl3XrW5BfFGj4NkT9d9a2gTqcExhme/08GxEoDpuIG6yxrwsg6AIClX7Fy+lRQDasY87bFSG3kLPR6pmeaTO/MH0ma8wpAfG6db/x6nhnVjDfXw8cOcz6dZOGq6boDuMRj9J02bFl/pi88YuwYg/lPekrCRbEvApC2Lg38QYFwhgPHawgIn0XOIC39TokiUEFJO/YW4/CfuROsZ0nOVzdZly4YueOv3IrSbq96Sb4QbM3qV7kfikHxr6FV6No1E56sHgMA1YGu66Mdvbvza2uKPM5ktaCedifGtfk=
  app: deeprog
  on:
    repo: deeprog/goalify
