default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: goalify_development
  pool: 5

test: &test
  <<: *default
  database: goalify_test

production:
  <<: *default
  database: goalify_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] %>
cucumber:
  <<: *test